project 'OversimplifiedDemo.xcodeproj'
workspace 'OversimplifiedDemo.xcworkspace'

platform :ios, :deployment_target => '9.0'

inhibit_all_warnings!
use_frameworks!

### Mixbox frameworks

def mixbox_ui_tests_pods
  mixbox_pod 'MixboxTestsFoundation'
  mixbox_pod 'MixboxUiTestsFoundation'
  mixbox_pod 'MixboxFoundation'
  mixbox_pod 'MixboxDi'
  
  pod 'SQLite.swift', :inhibit_warnings => true
  pod 'Dip', :inhibit_warnings => true
end

def mixbox_application_testability_and_ui_tests_common_pods
  mixbox_pod 'MixboxIpc'
  mixbox_pod 'MixboxIpcCommon'
  mixbox_pod 'MixboxUiKit'
  mixbox_pod 'MixboxAnyCodable'
end

def mixbox_application_testability_and_blackbox_testing_common_pods
  mixbox_application_testability_and_ui_tests_common_pods
  
  mixbox_pod 'MixboxBuiltinIpc'
end

def mixbox_application_testability_pods
  mixbox_application_testability_and_blackbox_testing_common_pods
  
  mixbox_pod 'MixboxTestability'
  mixbox_pod 'MixboxIpcSbtuiHost'
  mixbox_pod 'MixboxInAppServices'
end

def mixbox_blackbox_tests_pods
  mixbox_ui_tests_pods
  mixbox_application_testability_and_blackbox_testing_common_pods

  mixbox_pod 'MixboxIpcSbtuiClient'
  mixbox_pod 'MixboxBlack'
end

def mixbox_graybox_tests_pods
  mixbox_ui_tests_pods
  mixbox_application_testability_and_ui_tests_common_pods
  
  mixbox_pod 'MixboxGray'
end

def mixbox_whitebox_tests_pods
  # nothing is here yet
end

def mixbox_pod(name)
  hash = {}

  hash[:git] = 'https://github.com/avito-tech/Mixbox'
  hash[:commit] = ENV['MIXBOX_DEVELOPMENT_COMMIT']

  pod(name, hash)
end

# Targets

target 'OversimplifiedDemo' do
  mixbox_application_testability_pods
end

target 'OversimplifiedDemoUITests' do
  mixbox_blackbox_tests_pods
end
  
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name == 'Debug'
        # NOTE: You may want to add add '-Onone' for your debug builds so they will be compiled faster.
        
        # MIXBOX_ENABLE_IN_APP_SERVICES enables code for testing. You should not include that code in release builds.
        config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)', '-D', 'MIXBOX_ENABLE_IN_APP_SERVICES']
        
        # ENABLE_UITUNNEL is a same thing, but for SBTUITestTunnel library. We're planning to stop using it. If there is no such dependency now, remove this definition.
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'ENABLE_UITUNNEL=1', 'MIXBOX_ENABLE_IN_APP_SERVICES=1']
      end
    end
  end
end
